### ISSUE TITLE
Is there a plan to support LuaCov?

### ISSUE THREAD

**Issue by linrongbin16** [lewis6991/nvim-test#1]
hi, thanks to your work, does this test suit support LuaCov? (because it seems using busted internal)

Or is there plan to do this?

**Comment by lewis6991** [comment]
Not something I've ever considered and I've never used luacov

**Comment by linrongbin16** [comment]
FYI, busted naturally supports LuaCov, there is an argument `-c/--coverage` in busted manual: https://lunarmodules.github.io/busted/#usage.


If install busted with:

```bash
luarosks install luacov
luarocks install busted
```

Then it's ready to use.

> Personally I think code coverage is the next important step after having a Unit Test framework.

**Comment by lewis6991** [comment]
Sounds good.

I'm not against using LuaCOV or anything. I've just not had any experience with it yet.

**Comment by lewis6991** [comment]
It wasn't super straight forward but I've managed to add support.

The tricky thing was that nvim-test runs each test in a separate nvim instance and communicates over RPC so just needed to setup LuaCov on the remote instance.

**Comment by linrongbin16** [comment]
> It wasn't super straight forward but I've managed to add support.
> 
> The tricky thing was that nvim-test runs each test in a separate nvim instance and communicates over RPC so just needed to setup LuaCov on the remote instance.

Thank you!
